### ISSUE TITLE
Yaci v0.9.1-beta devkit uses protocol version 10

### ISSUE THREAD

**Issue by ilap** [bloxbean/yaci-devkit#65]
Yaci devkit uses protocol version 10 that has different costmodels for some newly introduced builtins.
This could affect the developer tools, as it returns 185 elements for V2 script's cost model  instead of the 175, and 251 for V3 instead of 223.

It should use the same as the current CH use the version 9.

```
shelley-genesis.json:    "protocolVersion" : {
shelley-genesis.json-      "major" : 10,
shelley-genesis.json-      "minor" : 0
shelley-genesis.json-    },
```

**Comment by satran004** [comment]
@ilap Thanks for pointing this out. I am looking into it.

I have updated the major version to 9 and tried.

Regarding the V3 cost model, it appears that the official V3 cost model contains 251 elements in  preprod/mainnet Conway Genesis file. I am updating DevKit accordingly.

https://book.play.dev.cardano.org/environments/mainnet/conway-genesis.json . Could you please verify this JSON file?

As for V2, as you mentioned, it returns 185 elements. It seems that the additional 10 elements are dummy values (max long).

```
           26308,
            10,
            9223372036854775807,
            9223372036854775807,
            9223372036854775807,
            9223372036854775807,
            9223372036854775807,
            9223372036854775807,
            9223372036854775807,
            9223372036854775807,
            9223372036854775807,
            9223372036854775807
```

Fyi, in alonzo-genesis.json, there are only 175 elements. But, it seems that the node (9.1.0) returns these extra elements when querying through the CLI or n2c.

**Comment by ilap** [comment]
> I have updated the major version to 9 and tried.
> 
> Regarding the V3 cost model, it appears that the official V3 cost model contains 251 elements in preprod/mainnet Conway Genesis file. I am updating DevKit accordingly.

I am not sure, but I think it only should retrieve 175 and 223 accordingly when the protocol version is set to 9. 
For 10, they should be 185 and 251, what is specified in the latest genesis files, that probably will be updated on the 2nd CHF.

We should ask @KtorZ as I have not dig deep into the major protocol version changes.

**Comment by ilap** [comment]
> As for V2, as you mentioned, it returns 185 elements. It seems that the additional 10 elements are dummy values (max long).

Does it retrieve 185 with the protocol version set to 9? Than, I am really confused, and IMO this behaviour would have impact on a lot of dev tools.

**Comment by satran004** [comment]
Thanks @ilap 

By default, the DevKit node transitions to the Conway era and all previous hard forks at epoch 0. In this case, we are getting these additional 10 elements in the Plutus V2 cost model.

But, if we start from the Babbage era at epoch 0 and then transition to the Conway HF at epoch 1, the Plutus V2 cost model is correct. This could be due to some change in the node. We will try to get more details.

It seems like we have following workarounds for now. I am working on this and will push a build soon.

### Workaround 1:

We can change the default template to start the Conway era at epoch 1. 

While starting the Conway era at epoch 1 is an option, the user would need to wait until epoch 1 (with the default epoch length of 500 slots/second) or start with a smaller epoch (for example, 20 slots). However, there will still be a need to wait for 1 epoch to enter the Conway era.

### Workaround 2:

Set the Conway Era HF at epoch 1 but shift the start time of the devnet back by 500 seconds. This way, the network will directly start at epoch 1, and block 1 will be in the Conway era.

Workaround 2 is working fine and requires a minor change. I am working on that now. This could also be a useful feature to test HFs in future releases.

**Comment by ilap** [comment]
Yeah, workaround 2 seems to me better too.

**Comment by satran004** [comment]
To resolve this issue, the following parameters have been set in node.properties. Please refer to the comments for details.

```
########################################################################################################
# Workaround for : https://github.com/bloxbean/yaci-devkit/issues/65
#
# The following parameters are enabled for a V2 cost model-related issue where there are 10 extra elements if the devnet
# is started with the Conway era at epoch 0. The following parameters are enabled to configure the Conway era hard fork (HF) at epoch 1.
# The network will start in the Babbage era and then hard fork (HF) to the Conway era at epoch 1.

# The shiftStartTimeBehind=true flag is enabled to shift the start time of the network to a time behind the current time by adjusting security parameter
# which changes the stability window. This is to speed up the process of reaching the Conway era.
#
# This should only be done in a development environment because if the stability window is larger than the epoch length, the reward/treasury calculations will be incorrect or ignored.
# Therefore, for a real multi-node network, you should start the network at the current time and allow it to reach the Conway era at epoch 1.
# So, the shiftStartTimeBehind flag should be "false" for non-development / multi-node networks.
#
#########################################################################################################

conwayHardForkAtEpoch=1
shiftStartTimeBehind=true

```

To test **reward calculation**, set "shiftStartTimeBehind" to false and use a smaller epoch length, such as 50. This way, epoch 1 will be reached in 50 seconds.

**Comment by ilap** [comment]
> To resolve this issue, the following parameters have been set in node.properties.

Hi @satran004, it looks like the `bloxbean/yaci-cli` and `bloxbean/yaci-viewer` version `0.9.2-beta` aren't available on hub.docker.com.

**Comment by satran004** [comment]
@ilap It's available now. https://github.com/bloxbean/yaci-devkit/releases/tag/v0.9.2-beta

Let me know if you face any issue.

**Comment by ilap** [comment]
> Let me know if you face any issue.

So far soo good. Thx for fixing it.
